# This is a basic workflow to help you get started with Actions

name: Build TrueNAS Scale

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub-hosted Ubuntu runner

    steps:
      - name: Maximize build disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          df -h

      - name: Checkout TrueNAS scale-build
        uses: actions/checkout@v4
        with:
          repository: truenas/scale-build
          ref: release/25.10-RC.1
          path: /scale-build
          
      - name: Move repo to /mnt
        run: |
          sudo cp -r $GITHUB_WORKSPACE/scale-build /mnt/scale-build

      - name: Run build inside Debian Bookworm
        uses: addnab/docker-run-action@v3
        with:
          image: debian:bookworm-slim
          options: --privileged -v /mnt:/mnt
          run: |
            cd /mnt/scale-build
            ls -la
            apt-get update
            apt-get install -y build-essential debootstrap git python3-pip python3-venv squashfs-tools unzip libjson-perl rsync libarchive-tools
            df -h
            mount
            make
