name: Build TrueNAS Scale image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo (for Dockerfile)
        uses: actions/checkout@v4

      - name: Build custom Debian Bookworm docker image
        run: |
          docker build -t truenas-build -f Dockerfile .

      - name: Checkout TrueNAS scale-build
        uses: actions/checkout@v4
        with:
          repository: truenas/scale-build
          ref: release/25.10-RC.1
          path: scale-build
          
      - name: Move repo to /mnt
        run: |
          sudo rm -rf /mnt/scale-build
          sudo cp -r $GITHUB_WORKSPACE/scale-build /mnt/scale-build

      - name: Checkout sources
        uses: addnab/docker-run-action@v3
        with:
          image: truenas-build
          options: --privileged -v /mnt:/mnt
          run: |
            cd /mnt/scale-build
            make checkout

      - name: Build .deb packages
        uses: addnab/docker-run-action@v3
        with:
          image: truenas-build
          options: --privileged -v /mnt:/mnt
          run: |
            cd /mnt/scale-build
            make packages

      - name: Build system update image
        uses: addnab/docker-run-action@v3
        with:
          image: truenas-build
          options: --privileged -v /mnt:/mnt
          run: |
            cd /mnt/scale-build
            make update

      - name: Build installation ISO image
        uses: addnab/docker-run-action@v3
        with:
          image: truenas-build
          options: --privileged -v /mnt:/mnt
          run: |
            cd /mnt/scale-build
            make iso
