# This is a basic workflow to help you get started with Actions

name: Build TrueNAS Scale

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub-hosted Ubuntu runner

    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true

      - name: Checkout TrueNAS scale-build
        uses: actions/checkout@v4
        with:
          repository: truenas/scale-build
          ref: release/25.10-RC.1

      - name: Run build inside Debian Bookworm
        uses: addnab/docker-run-action@v3
        with:
          image: debian:bookworm-slim
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            apt-get update
            apt-get install -y uild-essential debootstrap git python3-pip python3-venv squashfs-tools unzip libjson-perl rsync libarchive-tools
            make
